### ISSUE TITLE
Schema validation to return a nice message as well as tech detail

### ISSUE THREAD

**Issue by nick-gray** [hudson-taylor/ht-schema#8]
It would be nice if we could return some slightly nicer error messages as part of the schema validation errors. Ie if a field was supposed to be xyz and it ended up abc, we could give some additional info at discretion of the schema author what to tell the caller. There would also be the current error message which are still valid.

**Comment by nick-gray** [comment]
More accurate description of the 'nicer message' scenario as most messages are fine is this:
Schema contains a field like this:
        subnets: s.Array( [ s.String({ regex : /^(\d{1,3}\.){3}\d{1,3}\/\d{1,2}$/ }) ])

Returns this error message
Failed to parse schema.subnets: e is not defined

Rather than one of the other messages like this when passing in an invalid IP format:
'Failed to parse schema.ip: Got 100-100.10.10.10/32, did not match regex: /^(\\d{1,3}\\.){3}\\d{1,3}\\/\\d{1,2}$/',

**Comment by SomeoneWeird** [comment]
Oops! Indeed, this should be fixed in 3.2.1

**Comment by nick-gray** [comment]
nice one. thanks.
